#!/bin/bash
#SBATCH --account=quinlan-kp
#SBATCH --partition=quinlan-kp
#SBATCH -o %j-%N.out
#SBATCH -e %j-%N.err
#SBATCH --time=20:00:00

#########
#CLINVAR#
#########

python ../pathoscore.py annotate --scores ../score-sets/GRCh37/CCR/ccrs.autosomes.v2.20180420.bed.gz:CCR:4:max --scores ../score-sets/GRCh37/CCR/ccrs.xchrom.v2.20180420.bed.gz:CCR:4:max --scores ../score-sets/GRCh37/CADD/whole_genome_SNVs.tsv.gz:CADD:6:max --scores ../score-sets/GRCh37/CADD/InDels.tsv.gz:CADD:6:max --scores ../score-sets/GRCh37/DANN/DANN_whole_genome_SNVs.tsv.bgz:DANN:5:max --scores ../score-sets/GRCh37/GERP/gerp_rs.txt.gz:GERP:3:max --scores ../score-sets/GRCh37/MCAP/mcap.txt.gz:MCAP:5:max --scores ../score-sets/GRCh37/MPC/mpc.txt.gz:MPC:5:max --scores ../score-sets/GRCh37/MTR/mtrflatfile_1.0.txt.gz:MTR:11:max --scores ../score-sets/GRCh37/REVEL/revel.txt.gz:REVEL:7:max --scores ../score-sets/GRCh37/RVIS/rvis.bed.gz:RVIS:5:max --scores ../score-sets/GRCh37/VVP/VVP_scores_allChr.txt.gz:VVP:5:max --scores ../score-sets/GRCh37/aloft/aloft.txt.gz:aloft_het,aloft_lof,aloft_rec:5,6,7:max,max,max --scores ../score-sets/GRCh37/fathmm/fathmm/fathmm.txt.gz:fathmm_non,fathmm_coding:5,6:max,max --scores ../score-sets/GRCh37/fitcons/fitcons/fitcons.bed.gz:fitCons:4:max --scores ../score-sets/GRCh37/metasvm/MetaSVM.sorted.txt.gz:MetaSVM:5:max --scores ../score-sets/GRCh37/mis_Z/missensez.bed.gz:missense_z:5:max --scores ../score-sets/GRCh37/pLI/pLI.bed.gz:pLI:5:max --scores ../score-sets/GRCh37/phastCons/phastcons_vertebrate.txt.gz:phastCons:4:max --scores ../score-sets/GRCh37/polyphen2/Polyphen2_HVAR.sorted.txt.gz:polyphen2_hvar:5:max --scores ../score-sets/GRCh37/sift/SIFT_sorted.scores.txt.gz:SIFT:5:max ../truth-sets/GRCh37/clinvar/clinvar-benign.20170905.vcf.gz --prefix benign

python ../pathoscore.py annotate --scores ../score-sets/GRCh37/CCR/ccrs.autosomes.v2.20180420.bed.gz:CCR:4:max --scores ../score-sets/GRCh37/CCR/ccrs.xchrom.v2.20180420.bed.gz:CCR:4:max --scores ../score-sets/GRCh37/CADD/whole_genome_SNVs.tsv.gz:CADD:6:max --scores ../score-sets/GRCh37/CADD/InDels.tsv.gz:CADD:6:max --scores ../score-sets/GRCh37/DANN/DANN_whole_genome_SNVs.tsv.bgz:DANN:5:max --scores ../score-sets/GRCh37/GERP/gerp_rs.txt.gz:GERP:3:max --scores ../score-sets/GRCh37/MCAP/mcap.txt.gz:MCAP:5:max --scores ../score-sets/GRCh37/MPC/mpc.txt.gz:MPC:5:max --scores ../score-sets/GRCh37/MTR/mtrflatfile_1.0.txt.gz:MTR:11:max --scores ../score-sets/GRCh37/REVEL/revel.txt.gz:REVEL:7:max --scores ../score-sets/GRCh37/RVIS/rvis.bed.gz:RVIS:5:max --scores ../score-sets/GRCh37/VVP/VVP_scores_allChr.txt.gz:VVP:5:max --scores ../score-sets/GRCh37/aloft/aloft.txt.gz:aloft_het,aloft_lof,aloft_rec:5,6,7:max,max,max --scores ../score-sets/GRCh37/fathmm/fathmm/fathmm.txt.gz:fathmm_non,fathmm_coding:5,6:max,max --scores ../score-sets/GRCh37/fitcons/fitcons/fitcons.bed.gz:fitCons:4:max --scores ../score-sets/GRCh37/metasvm/MetaSVM.sorted.txt.gz:MetaSVM:5:max --scores ../score-sets/GRCh37/mis_Z/missensez.bed.gz:missense_z:5:max --scores ../score-sets/GRCh37/pLI/pLI.bed.gz:pLI:5:max --scores ../score-sets/GRCh37/phastCons/phastcons_vertebrate.txt.gz:phastCons:4:max --scores ../score-sets/GRCh37/polyphen2/Polyphen2_HVAR.sorted.txt.gz:polyphen2_hvar:5:max --scores ../score-sets/GRCh37/sift/SIFT_sorted.scores.txt.gz:SIFT:5:max ../truth-sets/GRCh37/clinvar/clinvar-pathogenic-likely_pathogenic.20170905.vcf.gz --prefix pathogenic

#########
#SAMOCHA#
#########

python ../pathoscore.py annotate --scores ../score-sets/GRCh37/CCR/ccrs.autosomes.v2.20180420.bed.gz:CCR:4:max --scores ../score-sets/GRCh37/CCR/ccrs.xchrom.v2.20180420.bed.gz:CCR:4:max --scores ../score-sets/GRCh37/CADD/whole_genome_SNVs.tsv.gz:CADD:6:max --scores ../score-sets/GRCh37/CADD/InDels.tsv.gz:CADD:6:max --scores ../score-sets/GRCh37/DANN/DANN_whole_genome_SNVs.tsv.bgz:DANN:5:max --scores ../score-sets/GRCh37/GERP/gerp_rs.txt.gz:GERP:3:max --scores ../score-sets/GRCh37/MCAP/mcap.txt.gz:MCAP:5:max --scores ../score-sets/GRCh37/MPC/mpc.txt.gz:MPC:5:max --scores ../score-sets/GRCh37/MTR/mtrflatfile_1.0.txt.gz:MTR:11:max --scores ../score-sets/GRCh37/REVEL/revel.txt.gz:REVEL:7:max --scores ../score-sets/GRCh37/RVIS/rvis.bed.gz:RVIS:5:max --scores ../score-sets/GRCh37/VVP/VVP_scores_allChr.txt.gz:VVP:5:max --scores ../score-sets/GRCh37/aloft/aloft.txt.gz:aloft_het,aloft_lof,aloft_rec:5,6,7:max,max,max --scores ../score-sets/GRCh37/fathmm/fathmm/fathmm.txt.gz:fathmm_non,fathmm_coding:5,6:max,max --scores ../score-sets/GRCh37/fitcons/fitcons/fitcons.bed.gz:fitCons:4:max --scores ../score-sets/GRCh37/metasvm/MetaSVM.sorted.txt.gz:MetaSVM:5:max --scores ../score-sets/GRCh37/mis_Z/missensez.bed.gz:missense_z:5:max --scores ../score-sets/GRCh37/pLI/pLI.bed.gz:pLI:5:max --scores ../score-sets/GRCh37/phastCons/phastcons_vertebrate.txt.gz:phastCons:4:max --scores ../score-sets/GRCh37/polyphen2/Polyphen2_HVAR.sorted.txt.gz:polyphen2_hvar:5:max --scores ../score-sets/GRCh37/sift/SIFT_sorted.scores.txt.gz:SIFT:5:max ../truth-sets/GRCh37/samocha/samocha.benign.vcf.gz --prefix benign

python ../pathoscore.py annotate --scores ../score-sets/GRCh37/CCR/ccrs.autosomes.v2.20180420.bed.gz:CCR:4:max --scores ../score-sets/GRCh37/CCR/ccrs.xchrom.v2.20180420.bed.gz:CCR:4:max --scores ../score-sets/GRCh37/CADD/whole_genome_SNVs.tsv.gz:CADD:6:max --scores ../score-sets/GRCh37/CADD/InDels.tsv.gz:CADD:6:max --scores ../score-sets/GRCh37/DANN/DANN_whole_genome_SNVs.tsv.bgz:DANN:5:max --scores ../score-sets/GRCh37/GERP/gerp_rs.txt.gz:GERP:3:max --scores ../score-sets/GRCh37/MCAP/mcap.txt.gz:MCAP:5:max --scores ../score-sets/GRCh37/MPC/mpc.txt.gz:MPC:5:max --scores ../score-sets/GRCh37/MTR/mtrflatfile_1.0.txt.gz:MTR:11:max --scores ../score-sets/GRCh37/REVEL/revel.txt.gz:REVEL:7:max --scores ../score-sets/GRCh37/RVIS/rvis.bed.gz:RVIS:5:max --scores ../score-sets/GRCh37/VVP/VVP_scores_allChr.txt.gz:VVP:5:max --scores ../score-sets/GRCh37/aloft/aloft.txt.gz:aloft_het,aloft_lof,aloft_rec:5,6,7:max,max,max --scores ../score-sets/GRCh37/fathmm/fathmm/fathmm.txt.gz:fathmm_non,fathmm_coding:5,6:max,max --scores ../score-sets/GRCh37/fitcons/fitcons/fitcons.bed.gz:fitCons:4:max --scores ../score-sets/GRCh37/metasvm/MetaSVM.sorted.txt.gz:MetaSVM:5:max --scores ../score-sets/GRCh37/mis_Z/missensez.bed.gz:missense_z:5:max --scores ../score-sets/GRCh37/pLI/pLI.bed.gz:pLI:5:max --scores ../score-sets/GRCh37/phastCons/phastcons_vertebrate.txt.gz:phastCons:4:max --scores ../score-sets/GRCh37/polyphen2/Polyphen2_HVAR.sorted.txt.gz:polyphen2_hvar:5:max --scores ../score-sets/GRCh37/sift/SIFT_sorted.scores.txt.gz:SIFT:5:max ../truth-sets/GRCh37/samocha/samocha.pathogenic.vcf.gz --prefix pathogenic

#######
#HOMSY#
#######

python ../pathoscore.py annotate --scores ../score-sets/GRCh37/CCR/ccrs.autosomes.v2.20180420.bed.gz:CCR:4:max --scores ../score-sets/GRCh37/CCR/ccrs.xchrom.v2.20180420.bed.gz:CCR:4:max --scores ../score-sets/GRCh37/CADD/whole_genome_SNVs.tsv.gz:CADD:6:max --scores ../score-sets/GRCh37/CADD/InDels.tsv.gz:CADD:6:max --scores ../score-sets/GRCh37/DANN/DANN_whole_genome_SNVs.tsv.bgz:DANN:5:max --scores ../score-sets/GRCh37/GERP/gerp_rs.txt.gz:GERP:3:max --scores ../score-sets/GRCh37/MCAP/mcap.txt.gz:MCAP:5:max --scores ../score-sets/GRCh37/MPC/mpc.txt.gz:MPC:5:max --scores ../score-sets/GRCh37/MTR/mtrflatfile_1.0.txt.gz:MTR:11:max --scores ../score-sets/GRCh37/REVEL/revel.txt.gz:REVEL:7:max --scores ../score-sets/GRCh37/RVIS/rvis.bed.gz:RVIS:5:max --scores ../score-sets/GRCh37/VVP/VVP_scores_allChr.txt.gz:VVP:5:max --scores ../score-sets/GRCh37/aloft/aloft.txt.gz:aloft_het,aloft_lof,aloft_rec:5,6,7:max,max,max --scores ../score-sets/GRCh37/fathmm/fathmm/fathmm.txt.gz:fathmm_non,fathmm_coding:5,6:max,max --scores ../score-sets/GRCh37/fitcons/fitcons/fitcons.bed.gz:fitCons:4:max --scores ../score-sets/GRCh37/metasvm/MetaSVM.sorted.txt.gz:MetaSVM:5:max --scores ../score-sets/GRCh37/mis_Z/missensez.bed.gz:missense_z:5:max --scores ../score-sets/GRCh37/pLI/pLI.bed.gz:pLI:5:max --scores ../score-sets/GRCh37/phastCons/phastcons_vertebrate.txt.gz:phastCons:4:max --scores ../score-sets/GRCh37/polyphen2/Polyphen2_HVAR.sorted.txt.gz:polyphen2_hvar:5:max --scores ../score-sets/GRCh37/sift/SIFT_sorted.scores.txt.gz:SIFT:5:max ../truth-sets/GRCh37/homsy/homsy.benign.vcf.gz --prefix benign

python ../pathoscore.py annotate --scores ../score-sets/GRCh37/CCR/ccrs.autosomes.v2.20180420.bed.gz:CCR:4:max --scores ../score-sets/GRCh37/CCR/ccrs.xchrom.v2.20180420.bed.gz:CCR:4:max --scores ../score-sets/GRCh37/CADD/whole_genome_SNVs.tsv.gz:CADD:6:max --scores ../score-sets/GRCh37/CADD/InDels.tsv.gz:CADD:6:max --scores ../score-sets/GRCh37/DANN/DANN_whole_genome_SNVs.tsv.bgz:DANN:5:max --scores ../score-sets/GRCh37/GERP/gerp_rs.txt.gz:GERP:3:max --scores ../score-sets/GRCh37/MCAP/mcap.txt.gz:MCAP:5:max --scores ../score-sets/GRCh37/MPC/mpc.txt.gz:MPC:5:max --scores ../score-sets/GRCh37/MTR/mtrflatfile_1.0.txt.gz:MTR:11:max --scores ../score-sets/GRCh37/REVEL/revel.txt.gz:REVEL:7:max --scores ../score-sets/GRCh37/RVIS/rvis.bed.gz:RVIS:5:max --scores ../score-sets/GRCh37/VVP/VVP_scores_allChr.txt.gz:VVP:5:max --scores ../score-sets/GRCh37/aloft/aloft.txt.gz:aloft_het,aloft_lof,aloft_rec:5,6,7:max,max,max --scores ../score-sets/GRCh37/fathmm/fathmm/fathmm.txt.gz:fathmm_non,fathmm_coding:5,6:max,max --scores ../score-sets/GRCh37/fitcons/fitcons/fitcons.bed.gz:fitCons:4:max --scores ../score-sets/GRCh37/metasvm/MetaSVM.sorted.txt.gz:MetaSVM:5:max --scores ../score-sets/GRCh37/mis_Z/missensez.bed.gz:missense_z:5:max --scores ../score-sets/GRCh37/pLI/pLI.bed.gz:pLI:5:max --scores ../score-sets/GRCh37/phastCons/phastcons_vertebrate.txt.gz:phastCons:4:max --scores ../score-sets/GRCh37/polyphen2/Polyphen2_HVAR.sorted.txt.gz:polyphen2_hvar:5:max --scores ../score-sets/GRCh37/sift/SIFT_sorted.scores.txt.gz:SIFT:5:max ../truth-sets/GRCh37/homsy/homsy.pathogenic.vcf.gz --prefix pathogenic

########
#WIGLER#
########

python ../pathoscore.py annotate --scores ../score-sets/GRCh37/CCR/ccrs.autosomes.v2.20180420.bed.gz:CCR:4:max --scores ../score-sets/GRCh37/CCR/ccrs.xchrom.v2.20180420.bed.gz:CCR:4:max --scores ../score-sets/GRCh37/CADD/whole_genome_SNVs.tsv.gz:CADD:6:max --scores ../score-sets/GRCh37/CADD/InDels.tsv.gz:CADD:6:max --scores ../score-sets/GRCh37/DANN/DANN_whole_genome_SNVs.tsv.bgz:DANN:5:max --scores ../score-sets/GRCh37/GERP/gerp_rs.txt.gz:GERP:3:max --scores ../score-sets/GRCh37/MCAP/mcap.txt.gz:MCAP:5:max --scores ../score-sets/GRCh37/MPC/mpc.txt.gz:MPC:5:max --scores ../score-sets/GRCh37/MTR/mtrflatfile_1.0.txt.gz:MTR:11:max --scores ../score-sets/GRCh37/REVEL/revel.txt.gz:REVEL:7:max --scores ../score-sets/GRCh37/RVIS/rvis.bed.gz:RVIS:5:max --scores ../score-sets/GRCh37/VVP/VVP_scores_allChr.txt.gz:VVP:5:max --scores ../score-sets/GRCh37/aloft/aloft.txt.gz:aloft_het,aloft_lof,aloft_rec:5,6,7:max,max,max --scores ../score-sets/GRCh37/fathmm/fathmm/fathmm.txt.gz:fathmm_non,fathmm_coding:5,6:max,max --scores ../score-sets/GRCh37/fitcons/fitcons/fitcons.bed.gz:fitCons:4:max --scores ../score-sets/GRCh37/metasvm/MetaSVM.sorted.txt.gz:MetaSVM:5:max --scores ../score-sets/GRCh37/mis_Z/missensez.bed.gz:missense_z:5:max --scores ../score-sets/GRCh37/pLI/pLI.bed.gz:pLI:5:max --scores ../score-sets/GRCh37/phastCons/phastcons_vertebrate.txt.gz:phastCons:4:max --scores ../score-sets/GRCh37/polyphen2/Polyphen2_HVAR.sorted.txt.gz:polyphen2_hvar:5:max --scores ../score-sets/GRCh37/sift/SIFT_sorted.scores.txt.gz:SIFT:5:max ../truth-sets/GRCh37/wigler-autism/wigler-autism.benign.vcf.gz --prefix benign

python ../pathoscore.py annotate --scores ../score-sets/GRCh37/CCR/ccrs.autosomes.v2.20180420.bed.gz:CCR:4:max --scores ../score-sets/GRCh37/CCR/ccrs.xchrom.v2.20180420.bed.gz:CCR:4:max --scores ../score-sets/GRCh37/CADD/whole_genome_SNVs.tsv.gz:CADD:6:max --scores ../score-sets/GRCh37/CADD/InDels.tsv.gz:CADD:6:max --scores ../score-sets/GRCh37/DANN/DANN_whole_genome_SNVs.tsv.bgz:DANN:5:max --scores ../score-sets/GRCh37/GERP/gerp_rs.txt.gz:GERP:3:max --scores ../score-sets/GRCh37/MCAP/mcap.txt.gz:MCAP:5:max --scores ../score-sets/GRCh37/MPC/mpc.txt.gz:MPC:5:max --scores ../score-sets/GRCh37/MTR/mtrflatfile_1.0.txt.gz:MTR:11:max --scores ../score-sets/GRCh37/REVEL/revel.txt.gz:REVEL:7:max --scores ../score-sets/GRCh37/RVIS/rvis.bed.gz:RVIS:5:max --scores ../score-sets/GRCh37/VVP/VVP_scores_allChr.txt.gz:VVP:5:max --scores ../score-sets/GRCh37/aloft/aloft.txt.gz:aloft_het,aloft_lof,aloft_rec:5,6,7:max,max,max --scores ../score-sets/GRCh37/fathmm/fathmm/fathmm.txt.gz:fathmm_non,fathmm_coding:5,6:max,max --scores ../score-sets/GRCh37/fitcons/fitcons/fitcons.bed.gz:fitCons:4:max --scores ../score-sets/GRCh37/metasvm/MetaSVM.sorted.txt.gz:MetaSVM:5:max --scores ../score-sets/GRCh37/mis_Z/missensez.bed.gz:missense_z:5:max --scores ../score-sets/GRCh37/pLI/pLI.bed.gz:pLI:5:max --scores ../score-sets/GRCh37/phastCons/phastcons_vertebrate.txt.gz:phastCons:4:max --scores ../score-sets/GRCh37/polyphen2/Polyphen2_HVAR.sorted.txt.gz:polyphen2_hvar:5:max --scores ../score-sets/GRCh37/sift/SIFT_sorted.scores.txt.gz:SIFT:5:max ../truth-sets/GRCh37/wigler-autism/wigler-autism.pathogenic.vcf.gz --prefix pathogenic

